### ISSUE TITLE
JsonPath.isDefinite(..) inconsistent behaviour

### ISSUE THREAD

**Issue by oleg-gr** [jayway/JsonPath#185]
`JsonPath.isDefinite("hello")` returns `true`, even though it's not a path at all (needs a check for `$` or function name). Expected return value: `false`

`JsonPath.isDefinite("$..hello[0]")` returns `false` (because of `..` operator) even though there is an index present at the end. Expected return value: `true`

**Comment by zline** [comment]
The second case is `false` because every component of a path must be definite for a path to be definite (== there can't be any indefinite-ness in a path).

**Comment by oleg-gr** [comment]
@zline, thank you for the response. Wasn't entirely sure about the second one. I don't think it's stated anywhere in Goessner's JsonPath definition what a definite path is (at least I couldn't find it, if you can please let me know). While I don't necessarily agree with you (since I think [0] makes the path very definite), I see how second case is not a bug. However, first case should still probably be fixed

**Comment by zline** [comment]
IMHO Goessner's JsonPath definition lacks almost everything in a part of semantics.
Indefinite path selects unpredictable number of nodes (e.g. because of deep scan operator `..`), I think that's the origin of term. And using subscription `[0]` for each of found nodes still gives unpredictable number of nodes.

**Comment by oleg-gr** [comment]
Agreed with @zline
