### ISSUE TITLE
JsonPathMatchers not in Maven Central for 2.1.0?

### ISSUE THREAD

**Issue by SingleShot** [jayway/JsonPath#186]
JsonPathMatchers appears to be missing from the 2.1.0 JAR.

**Comment by helsing** [comment]
Ah, yes. That's because the JsonPathMatchers were recently merged into master, but not yet published. They will be in next release.

(This is a recurring ambiguity when READMEs are describing both the published artifacts, as well as the  code pending to be released. But hopefully good enough, I hope?)

@kallestenflo Do you know when you plan to publish the next release?

**Comment by helsing** [comment]
If you want to try them out immediately, you can get them from here https://github.com/valid4j/json-path-matchers. Available on Maven Central as org.valid4j:json-path-matchers

**Comment by jochenberger** [comment]
I guess this can be closed, there is no further action required before the 2.2 release.
